-- Focused EcoDNA upgrade for reporter registration and rewards.
-- Safe to run more than once in an existing EcoDNA Supabase project.

create table if not exists public.ecodna_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text,
  role text not null default 'reporter' check (role in ('reporter', 'reviewer')),
  reward_points integer not null default 0 check (reward_points >= 0),
  created_at timestamptz not null default now()
);

alter table public.ecodna_profiles
  add column if not exists username text,
  add column if not exists reward_points integer not null default 0;

create unique index if not exists ecodna_profiles_username_idx
  on public.ecodna_profiles (lower(username))
  where username is not null;

alter table public.ecodna_profiles enable row level security;

create or replace function public.create_ecodna_profile()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.ecodna_profiles (user_id, username, role)
  values (new.id, nullif(lower(new.raw_user_meta_data->>'username'), ''), 'reporter')
  on conflict (user_id) do update set
    username = coalesce(public.ecodna_profiles.username, excluded.username);
  return new;
end;
$$;

drop trigger if exists ecodna_auth_user_created on auth.users;
create trigger ecodna_auth_user_created
  after insert on auth.users
  for each row execute procedure public.create_ecodna_profile();

insert into public.ecodna_profiles (user_id, role)
select id, 'reporter' from auth.users
on conflict (user_id) do nothing;

create table if not exists public.ecodna_rewards (
  id bigint generated by default as identity primary key,
  report_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  points integer not null default 10 check (points > 0),
  reason text not null default 'Approved litter observation',
  awarded_at timestamptz not null default now()
);

create index if not exists ecodna_rewards_user_idx
  on public.ecodna_rewards (user_id, awarded_at desc);

alter table public.ecodna_rewards enable row level security;

create or replace view public.ecodna_reward_leaderboard as
select
  profile.username,
  profile.reward_points,
  count(reward.id)::integer as approved_reports,
  max(reward.awarded_at) as latest_reward_at
from public.ecodna_profiles as profile
left join public.ecodna_rewards as reward on reward.user_id = profile.user_id
where profile.role = 'reporter'
group by profile.user_id, profile.username, profile.reward_points
order by profile.reward_points desc, latest_reward_at asc nulls last;
